server:
  port: 8888

client:
  url: http://localhost:8080

product:
  product-config-folder-name: "product-configs"

document-template:
  global-template-folder-name: "global-document-templates"
  product-template-folder-name: "document-templates"
  product-inclusion-template-folder-name: "includes"

spring:
  cloud:
    config:
      server:
        git:
          uri: /Users/hqnguyen/Documents/WORKSPACE/home/product-config/
        prefix: /spring-configs
